
export const API_CALL = 'API_CALL';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';

export const TEST_API_CALL_SUCCESS = 'TEST_API_CALL_SUCCESS';

